<option value="General Practice">General Medicine</option>
<option value="Obstetrics And Gynaecology">Obstetrics/Gynaecology</option>
<!-- <option value="Pediatrics">Pediatrics</option> -->
<option value="Internal Medicine">Internal Medicine</option>
<option value="Surgery">Surgery</option>
<option value="General Laboratory">General Laboratory</option>
<option value="Pharmacy">Pharmacy</option>
<option value="Ultrasound Scan Services">Ultrasound Scan Services</option>
<!-- <option value="Any Other Services">Any Other Services</option> -->